version: 2
updates:
- package-ecosystem: gradle
  directory: "/annotation-file-utilities"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.checkerframework.annotatedlib:guava
    versions:
    - 30.0-jre
    - 30.1-jre
  - dependency-name: org.checkerframework:checker-qual
    versions:
    - 3.10.0
    - 3.11.0
    - 3.9.1
  - dependency-name: com.google.errorprone:error_prone_annotations
    versions:
    - 2.5.1
  - dependency-name: org.plumelib:plume-util
    versions:
    - 1.4.1
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.github.johnrengelman.shadow
    versions:
    - 6.1.0
